import Head from "next/head";
import { useEffect, useState } from "react";
import Header from "../components/Header/Header";
import ProfileBody from "../components/ProfileMian/Partitions/ProfileBody";
import ProfileHeader from "../components/ProfileMian/Partitions/ProfileHeader";
import { useRouter } from "next/router";
import { getBaseUrl } from "../config";
import { useGetProfileQuery } from "../Redux/feature/auth/authApi";

export default function Home() {
  const [profileDetail, setProfileDetail] = useState({});
  const {data, isLoading, error} = useGetProfileQuery();  
  const router = useRouter();
  useEffect(() => {
    const token = localStorage.getItem("token");
    if (!token) {
      router.push("/auth/login");
    }    
  }, [router]);
  return (
    <div>
      <Head>
        <title>MRH BLOG</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <ProfileHeader profileDetail={data} />
      <ProfileBody profileDetail={data} />
    </div>
  );
}
